# Rubocop configuration for nu-agent
# Only applied to new and modified files during Console I/O refactoring

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'

# Style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout preferences
Layout/LineLength:
  Max: 120

# Metrics - reasonable limits for new code
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/nu/agent/console_io.rb'  # Complex input parsing requires longer methods

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'lib/nu/agent/console_io.rb'  # Single-file console I/O implementation

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Disable some overly strict cops
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/nu/agent/console_io.rb'  # Complex input parsing

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/nu/agent/console_io.rb'  # Escape sequence parsing has many branches

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/nu/agent/console_io.rb'  # Escape sequence parsing complexity
